name: See Free Cores

on:
  workflow_dispatch:

jobs:
  cpu-cores:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Display Resource Info
      run: |
        python -c "import os; print(os.cpu_count())"
        python -c "import psutil; print(f'Total Space: {psutil.disk_usage("/").total}')"
        python -c "import psutil; print(f'Free Space: {psutil.disk_usage("/").free}')"
