name: See Free Cores

on:
  workflow_dispatch:

jobs:
  cpu-cores:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install psutil 
    - name: Display Resource Info
      run: |
        python -c "import os; print(os.cpu_count())"
        python -c "import os; print(os.getcwd())"
        python -c "import psutil; print(psutil.disk_usage('/'))"
        python -c "import psutil; print(f'RAM: {psutil.virtual_memory()}')"
